on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ACba6b3c993ebc0a1e1f2d68defda108c1
          auth_token: 1bb2f9dd75144542b6b9db487e042e51
          to_whatsapp_no: 082116013197

        uses: ishween/whatsapp-push-notify-action@master
              
    
